In [112]:
import torch

print(torch.__version__)

2.11.0+cpu


In [113]:
# Creating Tensors

x = torch.tensor([1,2,3])

print(x)
print("Shape",x.shape)
print("Dtype", x.dtype)
print("Device", x.device)


tensor([1, 2, 3])
Shape torch.Size([3])
Dtype torch.int64
Device cpu


In [114]:
# Creating tensors with different Values

random_tensor = torch.rand(3, 4)
zeros_tensor = torch.zeros(2, 3)
ones_tensor = torch.ones(2, 3)

print("Random tensor:\n", random_tensor)
print("Shape:", random_tensor.shape)

print("\nZeros tensor:\n", zeros_tensor)

print("\nOnes tensor:\n", ones_tensor)


Random tensor:
 tensor([[0.5270, 0.4804, 0.6454, 0.6843],
        [0.5684, 0.0515, 0.4200, 0.8907],
        [0.3088, 0.7701, 0.3842, 0.2213]])
Shape: torch.Size([3, 4])

Zeros tensor:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [115]:
x_data = torch.tensor([[1, 2], [3, 4]])

ones_like_x = torch.ones_like(x_data)
random_like_x = torch.rand_like(x_data, dtype=torch.float)

print("x_data:\n", x_data)
print("ones_like:\n", ones_like_x)
print("rand_like:\n", random_like_x)

x_data:
 tensor([[1, 2],
        [3, 4]])
ones_like:
 tensor([[1, 1],
        [1, 1]])
rand_like:
 tensor([[0.3911, 0.2203],
        [0.5208, 0.3815]])


In [116]:
# concatenation
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("dim=0:")
print(torch.cat([a, b], dim=0))

print("\ndim=1:")
print(torch.cat([a, b], dim=1))

dim=0:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

dim=1:
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


In [118]:
# matrix multiplication
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])

C = A @ B

print(C)
print("Shape:", C.shape)

tensor([[19, 22],
        [43, 50]])
Shape: torch.Size([2, 2])


In [119]:
import torch

x = torch.tensor(3.0, requires_grad=True)
u = x ** 2
v = u * 5
v.backward()

print("x =", x)
print("u =", u)
print("v =", v)
print("gradient =", x.grad)

x = tensor(3., requires_grad=True)
u = tensor(9., grad_fn=<PowBackward0>)
v = tensor(45., grad_fn=<MulBackward0>)
gradient = tensor(30.)


In [120]:
import torch

x = torch.tensor(3.0, requires_grad=False )
u = x ** 2
v = u * 5
v.backward()

print("x =", x)
print("u =", u)
print("v =", v)
print("gradient =", x.grad)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn